Repository Santipy1204/Clase9, pull requests merged in 2023-11, with the labels that each got.

#12 Se crea la funcionalidad del botón recuperar contraseña
  datos/clientes.txt
  ventana1.py
Labels: bug, enhancement

#15 merge para unir la ventana 2 a Develop
  datos/clientes.txt
  ventana1.py
  ventana2.py
Labels: bug, enhancement

#17 Revissar y hacer el merge del branch tabla-usuarios en develop
  datos/clientes.txt
  ventana2.py
  ventana3.py
Labels: duplicate, enhancement

#20 Se hace el merge de ventana4 clase12, que contiene todas las anteriores clases y la pasamos al main
  .gitignore
  cliente.py
  datos/clientes.txt
  ventana1.py
  ventana2.py
  ventana3.py
  ventana4.py
Labels: bug, enhancement, help wanted
